// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efkxbixaldhdyiwvmwjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVma3hiaXhhbGRoZHlpd3Ztd2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjkzMjEsImV4cCI6MjA2NjEwNTMyMX0.mCxj6iRSIeFMVaf75aBIxtZtCCnH5nIcg1MdFdYU1AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);